# Generated by Django 4.1.7 on 2024-02-29 19:23

import django.core.validators
from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Group name')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Lesson name')),
                ('video_link', models.URLField(validators=[django.core.validators.URLValidator(message="Your link doesn't look like a valid url.")], verbose_name='Video link')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product name')),
                ('start_time', models.DateTimeField(validators=[products.validators.validate_start_time], verbose_name='Start time')),
                ('cost', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Cost of a product must be a positive number')], verbose_name='Cost of a product')),
                ('max_students', models.PositiveSmallIntegerField(verbose_name='Maximum number of students in a group')),
                ('min_students', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message="Group can't be less than one person.")], verbose_name='Minimum number of students in a group')),
            ],
        ),
    ]
